version: '3'
services:
  flask-app:
    image: python
    working_dir: /app
    volumes:
      - ../backend:/app
    network_mode: host
    command: bash -c "pip install Flask Flask-Cors && python main.py"

  react-app:
    image: node:14
    working_dir: /app
    volumes:
      - ../frontend:/app
    network_mode: host
    command: bash -c "npm install && npm start"